### ISSUE TITLE
Start/Stop button is bugged

### ISSUE THREAD

**Issue by xe1os** [Natxo09/CS2Server-Creator#3]
Hi,

Button still shows Stop when the server console is closed. It doesn't change to Start to start the server again.

And also the status below shows as Running........

Thank you.

**Comment by Natxo09** [comment]
> Hi,
> 
> Button still shows Stop when the server console is closed. It doesn't change to Start to start the server again.
> 
> And also the status below shows as Running........
> 
> Thank you.

I have a small dilemma with that, since if I make the application check if cs2.exe is running, you wouldn't be able to open more than one server. But of course, if you close the server from outside the program, the program has no way of knowing whether the server is closed or not. I'm thinking about how I can do it, and I hope the solution will be in the next update.
